package domaine;
// Generated 29 janv. 2016 14:52:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "prj")
public class Client implements java.io.Serializable {

	private Integer idClient;
	private Compte compte;
	private String nom;
	private String prenom;
	private String cin;
	private Set<Transaction> transactions = new HashSet<Transaction>(0);
	private Set<Solde> soldes = new HashSet<Solde>(0);

	public Client() {
	}

	public Client(Compte compte, String nom, String prenom, String cin) {
		this.compte = compte;
		this.nom = nom;
		this.prenom = prenom;
		this.cin = cin;
	}

	public Client(Compte compte, String nom, String prenom, String cin, Set<Transaction> transactions,
			Set<Solde> soldes) {
		this.compte = compte;
		this.nom = nom;
		this.prenom = prenom;
		this.cin = cin;
		this.transactions = transactions;
		this.soldes = soldes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idClient", unique = true, nullable = false)
	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login", nullable = false)
	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "cin", nullable = false, length = 50)
	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Solde> getSoldes() {
		return this.soldes;
	}

	public void setSoldes(Set<Solde> soldes) {
		this.soldes = soldes;
	}

}
