package domaine;
// Generated 29 janv. 2016 14:52:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Solde generated by hbm2java
 */
@Entity
@Table(name = "solde", catalog = "prj")
public class Solde implements java.io.Serializable {

	private Integer idSolde;
	private Client client;
	private int solde;

	public Solde() {
	}

	public Solde(Client client, int solde) {
		this.client = client;
		this.solde = solde;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSolde", unique = true, nullable = false)
	public Integer getIdSolde() {
		return this.idSolde;
	}

	public void setIdSolde(Integer idSolde) {
		this.idSolde = idSolde;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idClient", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@Column(name = "solde", nullable = false)
	public int getSolde() {
		return this.solde;
	}

	public void setSolde(int solde) {
		this.solde = solde;
	}

}
